### ISSUE TITLE
Gems not spawning?

### ISSUE THREAD

**Issue by hazerddex** [Daripher/Passive-Skill-Tree#133]
even at the highest spawn rate with all the gem chance up i've not seen a single one.

**Comment by Daripher** [comment]
Can not reproduce this issue, do you have any additional info on that?

**Comment by MemeLord32** [comment]
I think it's an incompatibility with Apotheosis. I have the latest of both Passive Skill Tree (and all requirements), and Apotheosis (and all requirements). To make sure it's not just RNG smacking me in the face, I set the base drop chance of gems in the config to 100%.

The effect should be: Everytime I mine an ore, I get a gem. With Apotheosis activated, I get no gems.

I tested if the problem was with any of Apotheosis's requirements, but I was still able to obtain gems with them, even though Apotheosis was disabled.

Summary:
Apotheosis + Passive Skill Tree = No Passive Skill Tree gem drops from ores.

I don't know if this is what hazerddex was experiencing or not, but this is what I got from my end.

Edit:
So, looking at JEI/EMI, the gems are disabled when Apotheosis Adventure module is enabled.

**Comment by MemeLord32** [comment]
So, looking at JEI/EMI, the gems are disabled when Apotheosis Adventure Mode module is enabled.

**Comment by DiogoHSS** [comment]
Why are gems disabled when Apeotheosis Adventure module is enabled?

And if gems are deliberately disabled because of apotheosis, could the miner skill tree give something else in place of higher drop chance from ores to not make it useless?
