### ISSUE TITLE
[1.20.1] Startup crash with Apotheosis

### ISSUE THREAD

**Issue by GreenCyborgNinja** [Daripher/Passive-Skill-Tree#146]
Mod crashes upon trying to go to world creation

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2024-01-07 22:27:08
Description: mouseClicked event handler

java.lang.NullPointerException: Trying to access unbound value: apotheosis:socket

**Comment by ZerausDG** [comment]
I have the same problem, when creating a new world or entering an already created one.

[crash-2024-01-07_18.35.46-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/13855292/crash-2024-01-07_18.35.46-client.txt)

**Comment by ZerausDG** [comment]
when I try to enter a world already created, it says that it is corrupted, but if I go back to the previous version 0.6.3.a, it works normally.

**Comment by neutralboolean** [comment]
I'm getting the same top-level complaint from the game when I load the game and try to start any single player map. As soon as I click single player it crashes.
[Crash text: crash-2024-01-07_20.04.15-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/13855582/crash-2024-01-07_20.04.15-client.txt)
This only happens when I have MineColonies enabled, as well. Just Apotheosis and Passive Skill Tree doesn't crash with this exception nor pose any sort of noticeable problem at all.

**Comment by ModernGamingWorld** [comment]
I crashed to, so Downgrade the mod to 0.6.3a-all and you wont crash for now
