### ISSUE TITLE
[1.20.1]: Add Apotheosis compatibility

### ISSUE THREAD

**Issue by Dad2004** [Daripher/Passive-Skill-Tree#53]
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/147294784/4d1efdb7-f3db-4f6e-8864-5be2672a7083)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/147294784/8dd95617-0d10-44ab-99e5-55e76dc11487)
-60% Enchantment Level Requirement with 15 eterna but still costs 30 levels to enchant

**Comment by Daripher** [comment]
There is no compatibility with Apotheosis on 1.20.x versions

**Comment by ArmouredDrood** [comment]
passive skill tree and apotheosis also have an interaction with the apotheosis gem of the royal family, which multiplies all stats by a percent. Instead of the intended stat increase, the gem multiplies attack damage by 20-30 times on mobs that spawn with apotheosis gem helmets and players with the gem in a helmet. 

I understand apotheosis compatability is not in your current plans.
Other mods that modify statistics in similar ways may encounter similar issues. 
One suggestion would be to zero index stat modifiers to avoid this issue. 

I very much enjoy your mod and the beautiful skill tree.
Thank you for your hard work. :)
