### ISSUE TITLE
Compact drawers related crash

### ISSUE THREAD

**Issue by Daripher** [Daripher/Passive-Skill-Tree#60]
Compact drawers auto craft things, without actual crafting grid.
This causes null pointer exception in PST recipes.
Simple null check should fix the issue.

**Comment by NanoCE** [comment]
Can confirm this issue occurs due to PST. Feel free to take a look at my crash log if you need more info. Originally went to FastSuite's issue github page but they explained it well and pointed out how its a bug with PST: https://github.com/Shadows-of-Fire/FastSuite/issues/31#event-10896465409

[crash-2023-11-07_22.54.18-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/13293361/crash-2023-11-07_22.54.18-client.txt)

**Comment by NanoCE** [comment]
Life in the village 3 modpack is waiting for this fix to be implemented. If you have the time @Daripher, please put out a release with it at you earliest convivence. (I am unaffiliated with the modpack team*)

**Comment by Daripher** [comment]
> Life in the village 3 modpack is waiting for this fix to be implemented. If you have the time @Daripher, please put out a release with it at you earliest convivence. (I am unaffiliated with the modpack team*)

Will do
